"""removed max _lenght

Revision ID: 55254b553c26
Revises: 77756ecd7981
Create Date: 2025-12-23 00:01:22.155253

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '55254b553c26'
down_revision = '77756ecd7981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
