"""added col to tool_call

Revision ID: 77f8366a0c62
Revises: 9e02726df76d
Create Date: 2026-01-16 21:52:06.604904

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77f8366a0c62'
down_revision = '9e02726df76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toolcall', sa.Column('message_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'toolcall', 'message', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'toolcall', type_='foreignkey')
    op.drop_column('toolcall', 'message_id')
    # ### end Alembic commands ###
