"""added message status

Revision ID: 849cd0ef1bfd
Revises: 25124367bf93
Create Date: 2025-12-30 22:36:07.805335

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '849cd0ef1bfd'
down_revision = '25124367bf93'
branch_labels = None
depends_on = None

status_enum = postgresql.ENUM('COMPLETE', 'FAILURE', 'STREAMING', name='status')
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind())
    op.add_column('message', sa.Column('status', sa.Enum('COMPLETE', 'FAILURE', 'STREAMING', name='status'), nullable=False, server_default='COMPLETE'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'status')
    status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
