"""changed target col to translation

Revision ID: dc0fce64b4c4
Revises: ad4538bfc8b0
Create Date: 2026-04-17 21:15:01.132192

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dc0fce64b4c4'
down_revision = 'ad4538bfc8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation', 'target', new_column_name='translation')
    op.add_column('translation', sa.Column('correct', sa.Integer(), nullable=True))
    op.add_column('translation', sa.Column('incorrect', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translation', 'translation', new_column_name='target')
    op.drop_column('translation', 'incorrect')
    op.drop_column('translation', 'correct')
    # ### end Alembic commands ###
